namespace EventLib;
public enum Category
{
	None = 0,
    Charity = 1,
    Concerts = 2,
    Parties = 3,
    Sports = 4,
    Conferences = 5,
    Exhibitions = 6,
    Workshops = 7,
    Festivals = 8,
    Meetups = 9,
    Fundraisers = 10,
    Classes = 11,
    ComedyShows = 12,
    TheaterAndPlays = 13,
    MoviesAndScreenings = 14,
    Gaming = 15,
    FoodAndDrink = 16,
    ArtAndCulture = 17,
    OutdoorActivities = 18,
    TechAndInnovation = 19,
    HealthAndWellness = 20,
}
